version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev && yarn dev"

  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=barbermanagement_dev_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
