version: '3'

services:
  deployment-prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - 80:3000
