version: '3'

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - 6543:5432
    environment:
      - POSTGRES_DB=barbermanagement_dev_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=${PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/node_modules/bcrypt/
    depends_on:
      - db
    command: sh -c "yarn migrate && yarn dev"
    tty: true
