version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - DATABASE_URI=postgresql://myuser:mypassword@db:5432/mydatabase?schema=public
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PORT=8080
      - CORS_ORIGIN=${CORS_ORIGIN}
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: sh -c "npx prisma migrate dev && yarn dev"

  db:
    image: postgres:15.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./pgdata:/var/lib/postgresql/data
