name: Sonar Checks
on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: yarn jest --coverage
      - name: SonarCloud Scan
        id: scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
      # print output of previous step which is an object, in a {key: value} format
      # eho ${{ steps.scan.outputs }} will print [object Object], and this doesn't work
      - name: Echo Output SonarCloud
        run: echo ${{join(steps.scan.outputs.*, '\n')}}

      - name: Set Output to env variable
        shell: bash
        run: echo "OUTPUT_SONAR=$(echo ${{ steps.scan.outputs }})" >> $GITHUB_ENV

      - name: Echo Output SonarCloud From Env
        run: echo ${{ env.OUTPUT_SONAR }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_MESSAGE: ${{join(steps.scan.outputs.*, '\n')}}
          SLACK_TITLE: Sonar Results
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

  # messageSlack:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notification Slack
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: github
  #         SLACK_TITLE: Backend
  #         SLACK_USERNAME: BotRepo
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_MESSAGE: 'Backend has been updated!'
