name: Sonar Checks
on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Test and coverage
        run: yarn jest --coverage
      - name: SonarCloud Scan
        id: scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}
      # print output of previous step, to help with debugging
      - name: Echo Output SonarCloud Scan
        run: echo ${{ steps.scan.outputs }}

      - name: Set Output to env variable
        shell: bash
        run: echo "OUTPUT_SONAR=$(echo ${{ steps.scan.outputs }})" >> $GITHUB_ENV

      - name: Echo Output SonarCloud From Env
        run: echo ${{ env.OUTPUT_SONAR }}

  # messageSlack:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Notification Slack
  #       uses: rtCamp/action-slack-notify@v2
  #       env:
  #         SLACK_CHANNEL: github
  #         SLACK_TITLE: Backend
  #         SLACK_USERNAME: BotRepo
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         SLACK_MESSAGE: 'Backend has been updated!'
